apiVersion: v1
kind: ConfigMap
metadata:
  name: app-gateway-config
  labels:
    app: app-gateway
data:
  RUST_LOG: info
  APP_ENV: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gateway
  template:
    metadata:
      labels:
        app: app-gateway
    spec:
      containers:
        - name: app-gateway
          image: murilocosta/huasteka-pahtecatl
          ports:
            - containerPort: 9705
          envFrom:
            - configMapRef:
                name: app-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-gateway
  labels:
    app: app-gateway
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9705
      targetPort: 9705
  selector:
    app: app-gateway
