apiVersion: v1
kind: ConfigMap
metadata:
  name: app-auth-config
  labels:
    app: app-auth
data:
  DATABASE_URL: postgres://huasteka:Q5yXSuuKVHlukd4@postgres-db:5432/app_auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-auth
  template:
    metadata:
      labels:
        app: app-auth
    spec:
      containers:
        - name: app-auth
          image: murilocosta/huasteka-zacatzontli
          ports:
            - containerPort: 1337
          envFrom:
            - configMapRef:
                name: app-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-auth
  labels:
    app: app-auth
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9701
      targetPort: 1337
  selector:
    app: app-auth
