apiVersion: v1
kind: ConfigMap
metadata:
  name: app-sales-config
  labels:
    app: app-sales
data:
  DB_CONNECTION: pgsql
  DB_HOST: postgres-db
  DB_PORT: "5432"
  DB_DATABASE: app_sales
  DB_USERNAME: huasteka
  DB_PASSWORD: Q5yXSuuKVHlukd4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-sales
  template:
    metadata:
      labels:
        app: app-sales
    spec:
      containers:
        - name: app-sales
          image: murilocosta/huasteka-huitzilopochtli
          ports:
            - containerPort: 9704
          envFrom:
            - configMapRef:
                name: app-sales-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-sales
  labels:
    app: app-sales
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9704
      targetPort: 9704
  selector:
    app: app-sales
